version: '3.8'
services:
#  postgres:
#    container_name: postgres-sql-bsn
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      PGDATA: /var/lib/postgresql/data
#      POSTGRES_DB: book_social_network
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    networks:
#      - spring-demo


#  pgadmin:
#    container_name: pgadmin-bsn
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ayedoussama2002@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#     - "5050:80"



  maildev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
    postgres:
      driver: local
networks:
    spring-demo:
        driver: bridge
