spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  springdoc:
    default-produces-media-type: application/json



server:
  servlet:
    context-path: /api/v1






#  datasource:
#    url: jdbc:mysql://localhost:3306/book-network?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create # ou "create" si vous voulez que Hibernate crée automatiquement les tables
#    show-sql: true # pour afficher les requêtes SQL dans la console
#    properties:
#      hibernate:
#        format_sql: true # pour formater les requêtes SQL